//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Matriculas
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DBMatricula2Entities : DbContext
    {
        public DBMatricula2Entities()
            : base("name=DBMatricula2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tb_Cursos> Tb_Cursos { get; set; }
        public virtual DbSet<Tb_Especialidad> Tb_Especialidad { get; set; }
        public virtual DbSet<Tb_Estudiantes> Tb_Estudiantes { get; set; }
        public virtual DbSet<Tb_Horario> Tb_Horario { get; set; }
        public virtual DbSet<Tb_Matricula> Tb_Matricula { get; set; }
        public virtual DbSet<Tb_Periodo> Tb_Periodo { get; set; }
        public virtual DbSet<Tb_Profesores> Tb_Profesores { get; set; }
        public virtual DbSet<Tb_Seccion> Tb_Seccion { get; set; }
        public virtual DbSet<Tb_Sede> Tb_Sede { get; set; }
        public virtual DbSet<Tb_Ubigeo> Tb_Ubigeo { get; set; }
        public virtual DbSet<Tb_Usuario> Tb_Usuario { get; set; }
    
        public virtual int usp_ActualizarCursos(string vcod, string vdes, Nullable<int> vcred, string vUsu_ult_mod, Nullable<bool> vEst_Cur)
        {
            var vcodParameter = vcod != null ?
                new ObjectParameter("vcod", vcod) :
                new ObjectParameter("vcod", typeof(string));
    
            var vdesParameter = vdes != null ?
                new ObjectParameter("vdes", vdes) :
                new ObjectParameter("vdes", typeof(string));
    
            var vcredParameter = vcred.HasValue ?
                new ObjectParameter("vcred", vcred) :
                new ObjectParameter("vcred", typeof(int));
    
            var vUsu_ult_modParameter = vUsu_ult_mod != null ?
                new ObjectParameter("vUsu_ult_mod", vUsu_ult_mod) :
                new ObjectParameter("vUsu_ult_mod", typeof(string));
    
            var vEst_CurParameter = vEst_Cur.HasValue ?
                new ObjectParameter("vEst_Cur", vEst_Cur) :
                new ObjectParameter("vEst_Cur", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ActualizarCursos", vcodParameter, vdesParameter, vcredParameter, vUsu_ult_modParameter, vEst_CurParameter);
        }
    
        public virtual int usp_ActualizarEstudiantes(string vcod, string vnom, string vape, string vtel, string vemail, string vId_Ubi, byte[] vfoto, string vdir, Nullable<System.DateTime> vFec_Nac, string vdni, string vUsu_ult_mod, Nullable<bool> vEst_Est)
        {
            var vcodParameter = vcod != null ?
                new ObjectParameter("vcod", vcod) :
                new ObjectParameter("vcod", typeof(string));
    
            var vnomParameter = vnom != null ?
                new ObjectParameter("vnom", vnom) :
                new ObjectParameter("vnom", typeof(string));
    
            var vapeParameter = vape != null ?
                new ObjectParameter("vape", vape) :
                new ObjectParameter("vape", typeof(string));
    
            var vtelParameter = vtel != null ?
                new ObjectParameter("vtel", vtel) :
                new ObjectParameter("vtel", typeof(string));
    
            var vemailParameter = vemail != null ?
                new ObjectParameter("vemail", vemail) :
                new ObjectParameter("vemail", typeof(string));
    
            var vId_UbiParameter = vId_Ubi != null ?
                new ObjectParameter("vId_Ubi", vId_Ubi) :
                new ObjectParameter("vId_Ubi", typeof(string));
    
            var vfotoParameter = vfoto != null ?
                new ObjectParameter("vfoto", vfoto) :
                new ObjectParameter("vfoto", typeof(byte[]));
    
            var vdirParameter = vdir != null ?
                new ObjectParameter("vdir", vdir) :
                new ObjectParameter("vdir", typeof(string));
    
            var vFec_NacParameter = vFec_Nac.HasValue ?
                new ObjectParameter("vFec_Nac", vFec_Nac) :
                new ObjectParameter("vFec_Nac", typeof(System.DateTime));
    
            var vdniParameter = vdni != null ?
                new ObjectParameter("vdni", vdni) :
                new ObjectParameter("vdni", typeof(string));
    
            var vUsu_ult_modParameter = vUsu_ult_mod != null ?
                new ObjectParameter("vUsu_ult_mod", vUsu_ult_mod) :
                new ObjectParameter("vUsu_ult_mod", typeof(string));
    
            var vEst_EstParameter = vEst_Est.HasValue ?
                new ObjectParameter("vEst_Est", vEst_Est) :
                new ObjectParameter("vEst_Est", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ActualizarEstudiantes", vcodParameter, vnomParameter, vapeParameter, vtelParameter, vemailParameter, vId_UbiParameter, vfotoParameter, vdirParameter, vFec_NacParameter, vdniParameter, vUsu_ult_modParameter, vEst_EstParameter);
        }
    
        public virtual int usp_ActualizarProfesor(string vcod, string vnom, string vape, byte[] vfoto, string vdir, string vemail, Nullable<System.DateTime> vFec_Nac, string vdni, string vCod_Espc, string vId_Ubi, string vUsu_Ult_Mod, Nullable<bool> vEst)
        {
            var vcodParameter = vcod != null ?
                new ObjectParameter("vcod", vcod) :
                new ObjectParameter("vcod", typeof(string));
    
            var vnomParameter = vnom != null ?
                new ObjectParameter("vnom", vnom) :
                new ObjectParameter("vnom", typeof(string));
    
            var vapeParameter = vape != null ?
                new ObjectParameter("vape", vape) :
                new ObjectParameter("vape", typeof(string));
    
            var vfotoParameter = vfoto != null ?
                new ObjectParameter("vfoto", vfoto) :
                new ObjectParameter("vfoto", typeof(byte[]));
    
            var vdirParameter = vdir != null ?
                new ObjectParameter("vdir", vdir) :
                new ObjectParameter("vdir", typeof(string));
    
            var vemailParameter = vemail != null ?
                new ObjectParameter("vemail", vemail) :
                new ObjectParameter("vemail", typeof(string));
    
            var vFec_NacParameter = vFec_Nac.HasValue ?
                new ObjectParameter("vFec_Nac", vFec_Nac) :
                new ObjectParameter("vFec_Nac", typeof(System.DateTime));
    
            var vdniParameter = vdni != null ?
                new ObjectParameter("vdni", vdni) :
                new ObjectParameter("vdni", typeof(string));
    
            var vCod_EspcParameter = vCod_Espc != null ?
                new ObjectParameter("vCod_Espc", vCod_Espc) :
                new ObjectParameter("vCod_Espc", typeof(string));
    
            var vId_UbiParameter = vId_Ubi != null ?
                new ObjectParameter("vId_Ubi", vId_Ubi) :
                new ObjectParameter("vId_Ubi", typeof(string));
    
            var vUsu_Ult_ModParameter = vUsu_Ult_Mod != null ?
                new ObjectParameter("vUsu_Ult_Mod", vUsu_Ult_Mod) :
                new ObjectParameter("vUsu_Ult_Mod", typeof(string));
    
            var vEstParameter = vEst.HasValue ?
                new ObjectParameter("vEst", vEst) :
                new ObjectParameter("vEst", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ActualizarProfesor", vcodParameter, vnomParameter, vapeParameter, vfotoParameter, vdirParameter, vemailParameter, vFec_NacParameter, vdniParameter, vCod_EspcParameter, vId_UbiParameter, vUsu_Ult_ModParameter, vEstParameter);
        }
    
        public virtual ObjectResult<usp_ConsultarCursos_Result> usp_ConsultarCursos(string vcod)
        {
            var vcodParameter = vcod != null ?
                new ObjectParameter("vcod", vcod) :
                new ObjectParameter("vcod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ConsultarCursos_Result>("usp_ConsultarCursos", vcodParameter);
        }
    
        public virtual ObjectResult<usp_ConsultarEstudiantes_Result> usp_ConsultarEstudiantes(string vcod)
        {
            var vcodParameter = vcod != null ?
                new ObjectParameter("vcod", vcod) :
                new ObjectParameter("vcod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ConsultarEstudiantes_Result>("usp_ConsultarEstudiantes", vcodParameter);
        }
    
        public virtual ObjectResult<usp_ConsultarProfesor_Result> usp_ConsultarProfesor(string vcod)
        {
            var vcodParameter = vcod != null ?
                new ObjectParameter("vcod", vcod) :
                new ObjectParameter("vcod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ConsultarProfesor_Result>("usp_ConsultarProfesor", vcodParameter);
        }
    
        public virtual ObjectResult<usp_ConsultartCursos_Result> usp_ConsultartCursos(string vcod)
        {
            var vcodParameter = vcod != null ?
                new ObjectParameter("vcod", vcod) :
                new ObjectParameter("vcod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ConsultartCursos_Result>("usp_ConsultartCursos", vcodParameter);
        }
    
        public virtual ObjectResult<usp_ConsultarUsuario_Result> usp_ConsultarUsuario(string login_Usu)
        {
            var login_UsuParameter = login_Usu != null ?
                new ObjectParameter("Login_Usu", login_Usu) :
                new ObjectParameter("Login_Usu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ConsultarUsuario_Result>("usp_ConsultarUsuario", login_UsuParameter);
        }
    
        public virtual int usp_EliminarCursos(string vcod)
        {
            var vcodParameter = vcod != null ?
                new ObjectParameter("vcod", vcod) :
                new ObjectParameter("vcod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_EliminarCursos", vcodParameter);
        }
    
        public virtual int usp_EliminarEstudiante(string vcod)
        {
            var vcodParameter = vcod != null ?
                new ObjectParameter("vcod", vcod) :
                new ObjectParameter("vcod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_EliminarEstudiante", vcodParameter);
        }
    
        public virtual int usp_EliminarProfesor(string vcod)
        {
            var vcodParameter = vcod != null ?
                new ObjectParameter("vcod", vcod) :
                new ObjectParameter("vcod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_EliminarProfesor", vcodParameter);
        }
    
        public virtual ObjectResult<usp_Especialidad_Descripcion_Result> usp_Especialidad_Descripcion()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Especialidad_Descripcion_Result>("usp_Especialidad_Descripcion");
        }
    
        public virtual int usp_InsertarCursos(string vdes, Nullable<int> vcred, string vUsu_Registro, Nullable<bool> vEst_Cur)
        {
            var vdesParameter = vdes != null ?
                new ObjectParameter("vdes", vdes) :
                new ObjectParameter("vdes", typeof(string));
    
            var vcredParameter = vcred.HasValue ?
                new ObjectParameter("vcred", vcred) :
                new ObjectParameter("vcred", typeof(int));
    
            var vUsu_RegistroParameter = vUsu_Registro != null ?
                new ObjectParameter("vUsu_Registro", vUsu_Registro) :
                new ObjectParameter("vUsu_Registro", typeof(string));
    
            var vEst_CurParameter = vEst_Cur.HasValue ?
                new ObjectParameter("vEst_Cur", vEst_Cur) :
                new ObjectParameter("vEst_Cur", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertarCursos", vdesParameter, vcredParameter, vUsu_RegistroParameter, vEst_CurParameter);
        }
    
        public virtual int usp_InsertarEstudiantes(string vnom, string vape, string vtel, string vemail, string vId_Ubi, byte[] vfoto, string vdir, string vFec_Nac, string vdni, string vUsu_Registro, Nullable<bool> vEst_Est)
        {
            var vnomParameter = vnom != null ?
                new ObjectParameter("vnom", vnom) :
                new ObjectParameter("vnom", typeof(string));
    
            var vapeParameter = vape != null ?
                new ObjectParameter("vape", vape) :
                new ObjectParameter("vape", typeof(string));
    
            var vtelParameter = vtel != null ?
                new ObjectParameter("vtel", vtel) :
                new ObjectParameter("vtel", typeof(string));
    
            var vemailParameter = vemail != null ?
                new ObjectParameter("vemail", vemail) :
                new ObjectParameter("vemail", typeof(string));
    
            var vId_UbiParameter = vId_Ubi != null ?
                new ObjectParameter("vId_Ubi", vId_Ubi) :
                new ObjectParameter("vId_Ubi", typeof(string));
    
            var vfotoParameter = vfoto != null ?
                new ObjectParameter("vfoto", vfoto) :
                new ObjectParameter("vfoto", typeof(byte[]));
    
            var vdirParameter = vdir != null ?
                new ObjectParameter("vdir", vdir) :
                new ObjectParameter("vdir", typeof(string));
    
            var vFec_NacParameter = vFec_Nac != null ?
                new ObjectParameter("vFec_Nac", vFec_Nac) :
                new ObjectParameter("vFec_Nac", typeof(string));
    
            var vdniParameter = vdni != null ?
                new ObjectParameter("vdni", vdni) :
                new ObjectParameter("vdni", typeof(string));
    
            var vUsu_RegistroParameter = vUsu_Registro != null ?
                new ObjectParameter("vUsu_Registro", vUsu_Registro) :
                new ObjectParameter("vUsu_Registro", typeof(string));
    
            var vEst_EstParameter = vEst_Est.HasValue ?
                new ObjectParameter("vEst_Est", vEst_Est) :
                new ObjectParameter("vEst_Est", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertarEstudiantes", vnomParameter, vapeParameter, vtelParameter, vemailParameter, vId_UbiParameter, vfotoParameter, vdirParameter, vFec_NacParameter, vdniParameter, vUsu_RegistroParameter, vEst_EstParameter);
        }
    
        public virtual int usp_InsertarProfesor(string vnom, string vape, byte[] vfoto, string vdir, string vemail, Nullable<System.DateTime> vFec_Nac, string vdni, string vCod_Espc, string vId_Ubi, string vUsu_Reg, Nullable<bool> vEst)
        {
            var vnomParameter = vnom != null ?
                new ObjectParameter("vnom", vnom) :
                new ObjectParameter("vnom", typeof(string));
    
            var vapeParameter = vape != null ?
                new ObjectParameter("vape", vape) :
                new ObjectParameter("vape", typeof(string));
    
            var vfotoParameter = vfoto != null ?
                new ObjectParameter("vfoto", vfoto) :
                new ObjectParameter("vfoto", typeof(byte[]));
    
            var vdirParameter = vdir != null ?
                new ObjectParameter("vdir", vdir) :
                new ObjectParameter("vdir", typeof(string));
    
            var vemailParameter = vemail != null ?
                new ObjectParameter("vemail", vemail) :
                new ObjectParameter("vemail", typeof(string));
    
            var vFec_NacParameter = vFec_Nac.HasValue ?
                new ObjectParameter("vFec_Nac", vFec_Nac) :
                new ObjectParameter("vFec_Nac", typeof(System.DateTime));
    
            var vdniParameter = vdni != null ?
                new ObjectParameter("vdni", vdni) :
                new ObjectParameter("vdni", typeof(string));
    
            var vCod_EspcParameter = vCod_Espc != null ?
                new ObjectParameter("vCod_Espc", vCod_Espc) :
                new ObjectParameter("vCod_Espc", typeof(string));
    
            var vId_UbiParameter = vId_Ubi != null ?
                new ObjectParameter("vId_Ubi", vId_Ubi) :
                new ObjectParameter("vId_Ubi", typeof(string));
    
            var vUsu_RegParameter = vUsu_Reg != null ?
                new ObjectParameter("vUsu_Reg", vUsu_Reg) :
                new ObjectParameter("vUsu_Reg", typeof(string));
    
            var vEstParameter = vEst.HasValue ?
                new ObjectParameter("vEst", vEst) :
                new ObjectParameter("vEst", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertarProfesor", vnomParameter, vapeParameter, vfotoParameter, vdirParameter, vemailParameter, vFec_NacParameter, vdniParameter, vCod_EspcParameter, vId_UbiParameter, vUsu_RegParameter, vEstParameter);
        }
    
        public virtual ObjectResult<usp_ListarCursos_Result> usp_ListarCursos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarCursos_Result>("usp_ListarCursos");
        }
    
        public virtual ObjectResult<usp_ListarEstudiantes_Result> usp_ListarEstudiantes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarEstudiantes_Result>("usp_ListarEstudiantes");
        }
    
        public virtual ObjectResult<usp_ListarProfesor_Result> usp_ListarProfesor()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarProfesor_Result>("usp_ListarProfesor");
        }
    
        public virtual ObjectResult<usp_Ubigeo_Departamentos_Result> usp_Ubigeo_Departamentos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Ubigeo_Departamentos_Result>("usp_Ubigeo_Departamentos");
        }
    
        public virtual ObjectResult<usp_Ubigeo_DistritosProvinciaDepartamento_Result> usp_Ubigeo_DistritosProvinciaDepartamento(string idDepartamento, string idProvincia)
        {
            var idDepartamentoParameter = idDepartamento != null ?
                new ObjectParameter("IdDepartamento", idDepartamento) :
                new ObjectParameter("IdDepartamento", typeof(string));
    
            var idProvinciaParameter = idProvincia != null ?
                new ObjectParameter("IdProvincia", idProvincia) :
                new ObjectParameter("IdProvincia", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Ubigeo_DistritosProvinciaDepartamento_Result>("usp_Ubigeo_DistritosProvinciaDepartamento", idDepartamentoParameter, idProvinciaParameter);
        }
    
        public virtual ObjectResult<usp_Ubigeo_ProvinciasDepartamento_Result> usp_Ubigeo_ProvinciasDepartamento(string idDepartamento)
        {
            var idDepartamentoParameter = idDepartamento != null ?
                new ObjectParameter("IdDepartamento", idDepartamento) :
                new ObjectParameter("IdDepartamento", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Ubigeo_ProvinciasDepartamento_Result>("usp_Ubigeo_ProvinciasDepartamento", idDepartamentoParameter);
        }
    }
}
